---
title: "final_markdown"
author: "Sophia Tannir & Arielle Dror"
date: "May 2, 2018"
output: html_document
---
Libraries and data:
```{r, message=FALSE}
library(tidyverse)
library(lubridate)
library(reshape2)
library(ggthemes)

##loading data
mac_data <- read_csv("dj_macleish_file.csv")

##converting character to date
mac_data <- mac_data %>%
  mutate(visit_date = mdy(visit_date))

#converting vehicle characters to integers
mac_data <- mac_data %>%
  mutate(vehicles = parse_number(vehicles)) %>%
  mutate(vehicles = parse_integer(vehicles))
```

Adding sums:
```{r}
mac_summary <- mac_data %>%
  summarise(total_fac = sum(num_fac),
            total_students = sum(num_stude, na.rm = TRUE),
            total_noncomm = sum(non_scomm),
            total_cars = sum(vehicles, na.rm = TRUE),
            total_class = sum(!is.na(class)),
            total_class_unique = n_distinct(class),
            total_visitors = (total_students + total_noncomm + total_fac))
```

Departments:

```{r}
##Arranges it by class
mac_dept <- mac_data %>%
  filter(!is.na(class)) %>%
  arrange(class)

##takes the first 3 chars to get the dept codes
mac_dept_unique <- mac_data %>%
  mutate(dept_codes=substring(mac_data$class, 0, 3)) %>%
  filter(!is.na(dept_codes))

##computes the number of unique depts
mac_total_dept <- mac_dept_unique %>%
 summarise(total_unique_dept_codes=n_distinct(dept_codes))

##calculates the counts of each dept 
mac_dept_freq <- mac_dept_unique %>%
  count(dept_codes) %>%
  arrange(desc(n))
```

Text Analysis

```{r}
mac_purpose <- mac_data %>%
  mutate(purpose = tolower(purpose)) %>%
  filter(!is.na(purpose))

purpose_counts <- mac_purpose %>%
  summarise(retreats = length(grep("retreat", mac_data[["purpose"]], 
                                   ignore.case = TRUE)),
            research = length(grep("research", mac_data[["purpose"]], 
                                   ignore.case = TRUE)),
            tour = length(grep("tour", mac_data[["purpose"]], 
                               ignore.case = TRUE)),
            survey = length(grep("survey", mac_data[["purpose"]], 
                                 ignore.case = TRUE)) + 
              length(grep("surveys", mac_data[["purpose"]], 
                          ignore.case = TRUE)),
            chestnut = length(grep("chestnut", mac_data[["purpose"]],
                                   ignore.case = TRUE)) +
              length(grep("chestnuts", mac_data[["purpose"]], 
                          ignore.case = TRUE)),
            fsf = length(grep("field station friday", mac_data[["purpose"]],
                              ignore.case = TRUE)),
            class = length(grep("class", mac_data[["purpose"]], 
                                ignore.case = TRUE)),
            orientation = length(grep("orientation", mac_data[["purpose"]],
                                      ignore.case = TRUE)),
            training = length(grep("training", mac_data[["purpose"]],
                                   ignore.case = TRUE)),
            project = length(grep("project", mac_data[["purpose"]], 
                                  ignore.case = TRUE)))
## transposing data frame into tidy form
purpose_counts <- t(purpose_counts)
purposes <- c("retreats", "research", "tour", "survey", "chestnut", "fsf",
              "class", "orientation", "training", "project")
purpose_counts <- as.data.frame(purpose_counts) %>%
  rename(counts = V1) %>%
  mutate(purpose = purposes)

```

Graphics:
```{r, warning=FALSE}
ggplot(purpose_counts, aes(x = purpose, y = counts, fill = purpose)) +
  geom_histogram(stat = "identity") +
  theme_economist()
```

<iframe src="https://public.tableau.com/views/freq_deptsample/Sheet1?:embed=y&:display_count=yes&publish=yes" width="800" height="600"></iframe>

